services:
  app-web:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yeniree0813
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./init-multiple-dbs.sql:/docker-entrypoint-initdb.d/init-multiple-dbs.sql

  rabbitmq:
    image: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.0
    command: start-dev
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    ports:
      - 8080:8080

    volumes:
      - ./keycloak_data:/opt/keycloak/data/


volumes:
  postgres-db-volume: 
  rabbitmq-volume:
  keycloak-data:
